### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by dinberuD** [devopsjourney23/my-srsproject-demo#1]
i can't connect with mongodb. here is the error: "open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused"

**Comment by devopsjourney23** [comment]
If you check at timestamp 16:35 of my youtube video, you'll see "connection refused" error until mongodb comes online.
did you wait for mongodb to come up? Tou can share screenshot of errors or complete log files.

https://www.youtube.com/watch?v=SrawJvOwUk0

**Comment by dinberuD** [comment]
yeah I have waited and it can't connect.

**Comment by dinberuD** [comment]
my ubuntu version is 22.04.4, may it be the reason?

**Comment by dinberuD** [comment]
here is my error. 
![git](https://github.com/devopsjourney23/my-srsproject-demo/assets/127215856/0e2c0ca7-aaac-46f8-a26f-87d4e7a84225)

**Comment by devopsjourney23** [comment]
You may try with recommended ubuntu release and see if that makes any difference. For me, it was pretty straight-forward to bring-up open5gs. Have you followed all steps or did you change any of open5gs config?

**Comment by dinberuD** [comment]
No I haven't changed any of open5gs config. Okay, let me try with a recommended ubuntu version. Thank you for your advice.

**Comment by dinberuD** [comment]
I have used ubuntu 22.04.1 but the error still persisted, and I haven't changed any config. May I need to run mongodb database as a local server?

**Comment by devopsjourney23** [comment]
Running as local server is not required. During weekend, I'll rebuild my setup again to see what else can be checked. You can share more details about your setup if it's different from what was in my video.

**Comment by dinberuD** [comment]
I was trying to do it on virtual machine and it has an issue. now I have fixed it on wsl. Thank you though.
