### ISSUE TITLE
Trying to install5gc a

### ISSUE THREAD

**Issue by ravisatyam2002** [devopsjourney23/my-srsproject-demo#2]
Hey 
I followed your steps to install 5gc via srsran project documentation but I am getting error. 

CONTAINER ID   IMAGE        COMMAND                  CREATED         STATUS                     PORTS                                       NAMES
0ff6bd351438   docker-5gc   "./open5gs_entrypoin…"   9 minutes ago   Up 9 minutes (unhealthy)   0.0.0.0:9999->9999/tcp, :::9999->9999/tcp   open5gs_5gc

open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb
open5gs_5gc  | nc: connect to 127.0.0.1 port 27017 (tcp) failed: Connection refused
open5gs_5gc  | waiting for mongodb

**Comment by devopsjourney23** [comment]
@ravisatyam2002 , Just now, I've tried building image from repo and able to start using exactly same steps without any issues.  
![image](https://github.com/user-attachments/assets/c7d14007-1014-4a15-8682-1a9a58bbff0c)

Also ensure, your ubuntu firewall is in inactive state (ufw status). If you can provide more information on your setup, if it's any different then what's mentioned in steps, I should be look into this further.

**Comment by ravisatyam2002** [comment]
@devopsjourney23 Thanks for your reply. I am using Window11 as host machine and running Virtualbox with 7.x version below config:-
Guest OS:- ubuntu 22.04
RAM;- 4GB
CPU-4
---
May i know you are using any type2 hypersior for installation. As per search there is something compatability issue with MongoDB5.x onwards as it needs AVX instruction which is not supported by virtual box. So have  installed mongodb4.x and build the Open5Gs from source and it worked. FYI, FW is inactive.  but wanted to install the docker version of Open5Gs.

**Comment by devopsjourney23** [comment]
@ravisatyam2002 , thanks for the info. I've been using vmware so far, so didn't face this issue.
