### ISSUE TITLE
Cannot find device "tun_srsue"

### ISSUE THREAD

**Issue by CS688** [devopsjourney23/my-srsproject-demo#3]
i input "ip netns exec ue1 ip route add default via 10.45.1.1 dev tun_srsue",it said i can not find device "tun_srsue"

**Comment by devopsjourney23** [comment]
> i input "ip netns exec ue1 ip route add default via 10.45.1.1 dev tun_srsue",it said i can not find device "tun_srsue"

It appears from your comment that you don't have any active session. Were you able to create UE session prior to running command?

**Comment by CS688** [comment]
> > i input "ip netns exec ue1 ip route add default via 10.45.1.1 dev tun_srsue",it said i can not find device "tun_srsue"
> 
> It appears from your comment that you don't have any active session. Were you able to create UE session prior to running command?

Yeah, I fund that i made a mistake in the config file. Thank u so much
