### ISSUE TITLE
GNU doesn't work

### ISSUE THREAD

**Issue by CS688** [devopsjourney23/my-srsproject-demo#4]
Why I click the play button,but nothing happened

**Comment by devopsjourney23** [comment]
> Why I click the play button,but nothing happened

You can share screenshot on what happening on your setup.

**Comment by CS688** [comment]
> > Why I click the play button,but nothing happened
> 
> You can share screenshot on what happening on your setup.

it works now.I don't know why, I just reboot the Ubuntu

**Comment by Shawn-cao741** [comment]
something wrong happened again. I click the execute button. But the ue was sitll in attahcing state.
![image](https://github.com/user-attachments/assets/aa7929a2-6d10-49f4-86d4-4a7dd8b79478)
